version: '3.8'
services:
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-container
      - redis-container
    ports:
      - 3003:3003
    networks:
      - common-network
  mysql-container:
    image: mysql
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: meeting_room_booking_system
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 3307:3306
    networks:
      - common-network
  redis-container:
    image: redis
    volumes:
      - ./redis-data:/data
    ports:
      - 6379:6379
    networks:
      - common-network
networks:
  common-network:
    driver: bridge
